// utils/buildEmbed.js
const { EmbedBuilder } = require('discord.js');
const logger = require('./logger');

// ============================================
// NAMED COLORS (with BYD-themed additions)
// ============================================
const namedColors = {
  // Standard colors
  red: 0xE74C3C,
  green: 0x2ECC71,
  blue: 0x3498DB,
  yellow: 0xF1C40F,
  orange: 0xE67E22,
  purple: 0x9B59B6,
  cyan: 0x1ABC9C,
  gray: 0x95A5A6,
  black: 0x000000,
  white: 0xFFFFFF,
  
  // BYD Brand Colors
  byd_blue: 0x00BFFF,
  byd_green: 0x00FF88,
  byd_gold: 0xFFD700,
  blade_battery: 0x00BFFF,
  
  // Status Colors
  success: 0x2ECC71,
  error: 0xE74C3C,
  warning: 0xF39C12,
  info: 0x3498DB,
  
  // Model Colors
  seal_blue: 0x0066CC,
  atto_green: 0x00CC66,
  dolphin_cyan: 0x00CCCC,
  han_red: 0xCC0000,
  seagull_orange: 0xFF6600,
  tang_purple: 0x9933CC,
  yangwang_black: 0x1A1A1A,
  
  // Discord Default
  discord: 0x5865F2,
  blurple: 0x7289DA,
};

// ============================================
// DISCLAIMER TEXT
// ============================================
const DISCLAIMERS = {
  ai_generated: '🤖 Content generated by AI. Information may not be 100% accurate.',
  automated: '🕒 This is an automated message.',
  prices: '💰 Prices and availability subject to change without notice.',
  specs: '⚙️ Specifications may vary by region.',
  eco: '🌱 Environmental impact figures are estimates.',
};

// ============================================
// PRE-BUILT EMBED TEMPLATES
// ============================================
const templates = {
  /**
   * Welcome embed for new members
   */
  welcome: (member) => ({
    title: `👋 Welcome to {{guildname}}, {{username}}!`,
    description: `Thanks for joining our BYD community!\n\nCheck out <#{{welcome_channel}}> to get started.\n\n${DISCLAIMERS.automated}`,
    color: 'byd_blue',
    thumbnail: { url: member?.user?.displayAvatarURL() },
    footer: { text: '⚡ BYD Blade Battery • Build Your Dreams' },
    timestamp: true,
  }),

  /**
   * Test drive confirmation
   */
  testDriveConfirm: (data) => ({
    title: '🚗 Test Drive Confirmed!',
    description: `Your test drive has been booked:\n\n📅 **Date:** {{date}}\n⏰ **Time:** {{time}}\n📍 **Location:** {{location}}\n🚙 **Model:** {{model}}`,
    color: 'success',
    fields: [
      { name: '📋 What to Bring', value: '• Valid driver\'s license\n• Proof of insurance\n• Comfortable shoes', inline: false },
      { name: '⏱️ Duration', value: '45-60 minutes', inline: true },
      { name: '💰 Cost', value: 'Free!', inline: true },
    ],
    footer: { text: 'A BYD advisor will contact you to confirm within 24 hours' },
    timestamp: true,
  }),

  /**
   * Quote display
   */
  quote: (quoteData) => ({
    title: `💰 Your BYD {{model}} Quote`,
    description: `Here's your personalized quote for the {{variant}} in {{color}}:`,
    color: 'byd_gold',
    fields: [
      { name: '🚙 Vehicle Price', value: '${{vehiclePrice}}', inline: true },
      { name: '📋 Fees', value: '${{fees}}', inline: true },
      { name: '🏛️ Tax', value: '${{tax}}', inline: true },
      { name: '💰 Incentives', value: '-${{incentives}}', inline: true },
      { name: '💵 Total', value: '**${{total}}**', inline: true },
      { name: '📅 Monthly (Est.)', value: '${{monthly}}/mo', inline: true },
    ],
    footer: { text: `{{incentivesList}} • ${DISCLAIMERS.prices}` },
    timestamp: true,
  }),

  /**
   * Error message
   */
  error: (message) => ({
    title: '❌ Oops!',
    description: message || 'Something went wrong. Please try again later.',
    color: 'error',
    footer: { text: 'Need help? Contact support in <#{{support_channel}}>' },
    timestamp: true,
  }),

  /**
   * Success message
   */
  success: (message) => ({
    title: '✅ Success!',
    description: message || 'Operation completed successfully.',
    color: 'success',
    footer: { text: 'Thank you for being part of our community!' },
    timestamp: true,
  }),

  /**
   * Auto post content
   */
  autoPost: (data) => ({
    title: data.title || '🚗 BYD Update',
    description: `${data.content}\n\n${DISCLAIMERS.ai_generated}`,
    color: data.source === 'fallback' ? 'orange' : 'byd_blue',
    image: data.image ? { url: data.image } : undefined,
    footer: { 
      text: data.source === 'fallback' 
        ? `📦 Pre-written Content • ${DISCLAIMERS.automated}` 
        : `🤖 AI Generated • ${DISCLAIMERS.automated} • Model: ${data.model || 'Unknown'}` 
    },
    timestamp: true,
  }),

  /**
   * Lead capture welcome
   */
  leadWelcome: (username) => ({
    title: `⚡ Welcome to the BYD Elite Circle, {{username}}!`,
    description: `You've been recognized as a **Lead** – that means you get **priority access** to exclusive offers and test drives.\n\n${DISCLAIMERS.automated}`,
    color: 'byd_gold',
    thumbnail: { url: '{{avatar}}' },
    footer: { text: '⚡ Blade Battery Technology • Trusted by 15,000+ drivers' },
    timestamp: true,
  }),

  /**
   * Giveaway announcement
   */
  giveaway: (prize, endTime, winners) => ({
    title: `🎁 GIVEAWAY: ${prize}`,
    description: `React with 🎉 to enter!\n\n**Ends:** <t:${Math.floor(endTime / 1000)}:R>\n**Winners:** ${winners}\n\n${DISCLAIMERS.automated}`,
    color: 'byd_gold',
    footer: { text: 'Good luck! 🍀' },
    timestamp: true,
  }),

  /**
   * Car giveaway announcement
   */
  carGiveaway: (data) => ({
    title: `🚗 CAR GIVEAWAY: BYD ${data.model}`,
    description: `Win a brand new BYD ${data.model}!\n\n**Value:** $${data.msrp?.toLocaleString()}\n**Color:** ${data.color}\n**Shipping:** Included\n**Ends:** <t:${Math.floor(data.endTime / 1000)}:R>\n\n${DISCLAIMERS.automated}`,
    color: 'byd_gold',
    image: data.image ? { url: data.image } : undefined,
    fields: [
      { name: '🏆 Winners', value: `${data.winners}`, inline: true },
      { name: '💵 Entry Fee', value: data.entryFee ? `$${data.entryFee}` : 'Free', inline: true },
      { name: '📋 Requirements', value: '• Must be 18+\n• Valid driver\'s license\n• Legal resident', inline: false },
      { name: '⚠️ Disclaimer', value: 'No purchase necessary to enter or win. Void where prohibited.', inline: false },
    ],
    footer: { text: 'Enter now for your chance to win!' },
    timestamp: true,
  }),

  /**
   * Maintenance announcement
   */
  maintenance: (duration, details) => ({
    title: '🔧 Maintenance Notice',
    description: `The bot will be undergoing scheduled maintenance.\n\n**Duration:** ~${duration} minutes\n**Reason:** ${details || 'System upgrades'}\n\nService will resume automatically.`,
    color: 'warning',
    footer: { text: 'We\'ll be back soon!' },
    timestamp: true,
  }),

  /**
   * Stats display
   */
  stats: (statsData) => ({
    title: '📊 Bot Statistics',
    description: 'Current system status and performance metrics:',
    color: 'byd_blue',
    fields: [
      { name: '📅 Uptime', value: statsData.uptime || 'Unknown', inline: true },
      { name: '📨 Posts', value: `Total: ${statsData.totalPosts || 0}\nSuccess: ${statsData.successRate || '0%'}`, inline: true },
      { name: '🤖 AI/Fallback', value: `API: ${statsData.apiPosts || 0}\nFallback: ${statsData.fallbackPosts || 0}`, inline: true },
      { name: '⏰ Last Post', value: statsData.lastPostTime || 'Never', inline: true },
      { name: '📡 Cache', value: `${statsData.cacheSize || 0} items`, inline: true },
    ],
    footer: { text: `${DISCLAIMERS.automated} • Stats refresh every 6h` },
    timestamp: true,
  }),
};

// ============================================
// HELPER FUNCTIONS
// ============================================

/**
 * Replace {{placeholders}} in a string with values from context.
 * @param {string} str - String with placeholders
 * @param {Object} vars - Variables to replace
 * @returns {string} - String with placeholders replaced
 */
function replacePlaceholders(str, vars) {
  if (!str || typeof str !== 'string') return str;
  let result = str;
  
  // Replace all placeholders with safety checks
  for (const [key, value] of Object.entries(vars)) {
    if (value !== undefined && value !== null) {
      const regex = new RegExp(`{{${key}}}`, 'g');
      const safeValue = String(value).replace(/[\\<>]/g, ''); // Sanitize HTML-like characters
      result = result.replace(regex, safeValue);
    }
  }
  
  // Remove any remaining placeholders
  result = result.replace(/{{[^}]+}}/g, '[unknown]');
  
  return result;
}

/**
 * Parse color value from various formats.
 * @param {string|number|Array} color - Color in various formats
 * @returns {number|null} - Parsed color integer
 */
function parseColor(color) {
  if (color === undefined || color === null) return null;
  
  // Number (hex)
  if (typeof color === 'number') {
    if (color >= 0 && color <= 0xFFFFFF) return color;
    return null;
  }
  
  // String
  if (typeof color === 'string') {
    // Hex string
    if (color.startsWith('#')) {
      const parsed = parseInt(color.slice(1), 16);
      return isNaN(parsed) ? null : parsed;
    }
    // Named color
    const lowerColor = color.toLowerCase();
    if (namedColors[lowerColor]) {
      return namedColors[lowerColor];
    }
  }
  
  // RGB array
  if (Array.isArray(color) && color.length === 3) {
    const [r, g, b] = color;
    if (r >= 0 && r <= 255 && g >= 0 && g <= 255 && b >= 0 && b <= 255) {
      return (r << 16) + (g << 8) + b;
    }
  }
  
  return null;
}

/**
 * Truncate string to Discord embed limits
 * @param {string} str - String to truncate
 * @param {number} maxLength - Maximum length
 * @returns {string} - Truncated string
 */
function truncateString(str, maxLength = 1024) {
  if (!str || str.length <= maxLength) return str;
  return str.substring(0, maxLength - 3) + '...';
}

/**
 * Build pagination row for multi-page embeds.
 * @param {number} currentPage - Current page index (0-based)
 * @param {number} totalPages - Total number of pages
 * @param {string} customIdPrefix - Prefix for button custom IDs
 * @returns {ActionRowBuilder} - Button row
 */
function buildPaginationRow(currentPage, totalPages, customIdPrefix = 'page') {
  const { ActionRowBuilder, ButtonBuilder, ButtonStyle } = require('discord.js');
  
  if (totalPages <= 1) return null;
  
  return new ActionRowBuilder().addComponents(
    new ButtonBuilder()
      .setCustomId(`${customIdPrefix}_prev`)
      .setLabel('◀ Previous')
      .setStyle(ButtonStyle.Secondary)
      .setDisabled(currentPage <= 0),
    new ButtonBuilder()
      .setCustomId(`${customIdPrefix}_info`)
      .setLabel(`${currentPage + 1} / ${totalPages}`)
      .setStyle(ButtonStyle.Secondary)
      .setDisabled(true),
    new ButtonBuilder()
      .setCustomId(`${customIdPrefix}_next`)
      .setLabel('Next ▶')
      .setStyle(ButtonStyle.Secondary)
      .setDisabled(currentPage >= totalPages - 1),
  );
}

/**
 * Validate embed size limits
 * @param {EmbedBuilder} embed - The embed to validate
 * @returns {boolean} - Whether the embed is within limits
 */
function validateEmbedSize(embed) {
  const MAX_EMBED_TOTAL = 6000; // Total character limit for all fields + description
  
  let totalLength = 0;
  if (embed.data.description) totalLength += embed.data.description.length;
  if (embed.data.title) totalLength += embed.data.title.length;
  if (embed.data.footer?.text) totalLength += embed.data.footer.text.length;
  if (embed.data.author?.name) totalLength += embed.data.author.name.length;
  
  if (embed.data.fields) {
    for (const field of embed.data.fields) {
      totalLength += (field.name?.length || 0) + (field.value?.length || 0);
    }
  }
  
  if (totalLength > MAX_EMBED_TOTAL) {
    logger.warn(`Embed total length (${totalLength}) exceeds Discord limit (${MAX_EMBED_TOTAL})`);
    return false;
  }
  
  return true;
}

// ============================================
// MAIN BUILD FUNCTION
// ============================================

/**
 * Build a Discord embed with template support and placeholder replacement.
 * @param {Object} embedData - Embed configuration
 * @param {Object} context - Context for placeholder replacement
 * @returns {EmbedBuilder} - Discord embed
 */
function buildEmbed(embedData = {}, context = {}) {
  if (!embedData || typeof embedData !== 'object') {
    logger.error('Invalid embedData provided to buildEmbed');
    return new EmbedBuilder().setColor(0xE74C3C).setDescription('Embed configuration error');
  }

  const embed = new EmbedBuilder();

  // Prepare replacement variables
  const { user, member, guild, channel, replacements = {} } = context;
  const vars = {
    username: user?.username || member?.user?.username || 'there',
    userTag: user?.tag || member?.user?.tag || 'user',
    userId: user?.id || member?.user?.id || '',
    userMention: user?.id ? `<@${user.id}>` : (member?.user?.id ? `<@${member.user.id}>` : '@user'),
    guildname: guild?.name || 'this server',
    guildId: guild?.id || '',
    channelname: channel?.name || 'this channel',
    channelMention: channel?.id ? `<#${channel.id}>` : '#channel',
    support_channel: process.env.SUPPORT_CHANNEL_ID || 'support',
    welcome_channel: process.env.WELCOME_CHANNEL_ID || 'welcome',
    avatar: user?.displayAvatarURL?.() || member?.user?.displayAvatarURL?.() || '',
    date: new Date().toLocaleDateString('en-US', { month: 'long', day: 'numeric', year: 'numeric' }),
    time: new Date().toLocaleTimeString('en-US', { hour: '2-digit', minute: '2-digit' }),
    ...replacements,
  };

  logger.debug(`Building embed with ${Object.keys(vars).length} variables`);

  const replace = (str) => replacePlaceholders(str, vars);

  // Title (max 256 characters)
  if (embedData.title) {
    const title = replace(embedData.title);
    embed.setTitle(truncateString(title, 256));
  }

  // Description (max 4096 characters)
  if (embedData.description) {
    const description = replace(embedData.description);
    embed.setDescription(truncateString(description, 4096));
  }

  // URL
  if (embedData.url) {
    embed.setURL(replace(embedData.url));
  }

  // Color
  const colorValue = parseColor(embedData.color);
  if (colorValue !== null) {
    embed.setColor(colorValue);
  } else if (embedData.color !== undefined) {
    embed.setColor(0x7289DA); // Default blurple
  }

  // Author (max 256 characters for name)
  if (embedData.author) {
    embed.setAuthor({
      name: truncateString(replace(embedData.author.name), 256),
      iconURL: embedData.author.iconURL ? replace(embedData.author.iconURL) : undefined,
      url: embedData.author.url ? replace(embedData.author.url) : undefined,
    });
  }

  // Thumbnail
  if (embedData.thumbnail?.url) {
    embed.setThumbnail(replace(embedData.thumbnail.url));
  }

  // Image
  if (embedData.image?.url) {
    embed.setImage(replace(embedData.image.url));
  }

  // Fields (max 25 fields, name max 256, value max 1024)
  if (embedData.fields && Array.isArray(embedData.fields)) {
    const limitedFields = embedData.fields.slice(0, 25);
    const replacedFields = limitedFields.map(field => ({
      name: truncateString(replace(field.name), 256),
      value: truncateString(replace(field.value), 1024),
      inline: field.inline || false,
    }));
    embed.addFields(replacedFields);
  }

  // Footer (max 2048 characters for text)
  if (embedData.footer) {
    const footerText = truncateString(
      replace(embedData.footer.text || embedData.footer), 
      2048
    );
    embed.setFooter({
      text: footerText,
      iconURL: embedData.footer.iconURL ? replace(embedData.footer.iconURL) : undefined,
    });
  }

  // Timestamp
  if (embedData.timestamp) {
    embed.setTimestamp(embedData.timestamp === true ? new Date() : new Date(embedData.timestamp));
  }

  // Validate size
  if (!validateEmbedSize(embed)) {
    logger.warn('Embed size exceeds Discord limits');
  }

  logger.debug(`Embed built successfully: "${embedData.title?.substring(0, 50) || 'No title'}"`);
  return embed;
}

// ============================================
// QUICK BUILDERS
// ============================================

/**
 * Build a simple success embed.
 * @param {string} message - Success message
 * @param {Object} context - Context for replacements
 * @returns {EmbedBuilder}
 */
function successEmbed(message, context = {}) {
  if (typeof message === 'object' && message !== null) {
    return buildEmbed(templates.success(message.message || 'Success'), { ...context, ...message });
  }
  return buildEmbed(templates.success(message), context);
}

/**
 * Build a simple error embed.
 * @param {string|Error} message - Error message or Error object
 * @param {Object} context - Context for replacements
 * @returns {EmbedBuilder}
 */
function errorEmbed(message, context = {}) {
  let errorMessage = '';
  
  if (message instanceof Error) {
    errorMessage = message.message;
    logger.error(`Error embed created for: ${errorMessage}`);
  } else if (typeof message === 'object' && message !== null) {
    errorMessage = message.message || 'Something went wrong';
    return buildEmbed(templates.error(errorMessage), { ...context, ...message });
  } else {
    errorMessage = message || 'Something went wrong';
  }
  
  return buildEmbed(templates.error(errorMessage), context);
}

/**
 * Build an auto post embed.
 * @param {Object} data - Auto post data
 * @param {Object} context - Context for replacements
 * @returns {EmbedBuilder}
 */
function autoPostEmbed(data, context = {}) {
  if (!data || !data.content) {
    logger.error('Invalid data for autoPostEmbed');
    return errorEmbed('Failed to generate auto post content');
  }
  return buildEmbed(templates.autoPost(data), context);
}

/**
 * Build a quote embed.
 * @param {Object} quoteData - Quote data
 * @param {Object} context - Context for replacements
 * @returns {EmbedBuilder}
 */
function quoteEmbed(quoteData, context = {}) {
  if (!quoteData || !quoteData.total) {
    logger.error('Invalid quote data');
    return errorEmbed('Quote data is incomplete');
  }
  return buildEmbed(templates.quote(quoteData), context);
}

/**
 * Build a stats embed.
 * @param {Object} statsData - Statistics data
 * @param {Object} context - Context for replacements
 * @returns {EmbedBuilder}
 */
function statsEmbed(statsData, context = {}) {
  return buildEmbed(templates.stats(statsData), context);
}

/**
 * Build a maintenance embed.
 * @param {number} duration - Duration in minutes
 * @param {string} details - Maintenance details
 * @returns {EmbedBuilder}
 */
function maintenanceEmbed(duration = 15, details = 'System upgrades') {
  return buildEmbed(templates.maintenance(duration, details));
}

// ============================================
// EXPORTS
// ============================================
module.exports = buildEmbed;
module.exports.templates = templates;
module.exports.colors = namedColors;
module.exports.disclaimers = DISCLAIMERS;
module.exports.success = successEmbed;
module.exports.error = errorEmbed;
module.exports.autoPost = autoPostEmbed;
module.exports.quote = quoteEmbed;
module.exports.stats = statsEmbed;
module.exports.maintenance = maintenanceEmbed;
module.exports.buildPaginationRow = buildPaginationRow;
module.exports.replacePlaceholders = replacePlaceholders;
module.exports.parseColor = parseColor;
module.exports.validateEmbedSize = validateEmbedSize;
module.exports.truncateString = truncateString;